# Generated by Django 5.2.3 on 2025-06-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=1)),
                ('cod_org', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('nome_set', models.CharField(max_length=100)),
                ('tipo_parceria', models.CharField(blank=True, max_length=10)),
                ('parceiro', models.CharField(blank=True, max_length=20)),
                ('primeiro_contato', models.DateTimeField()),
                ('ultimo_contato', models.DateTimeField()),
                ('limite_calculado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='ProdutoVendido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('venda_id', models.CharField(max_length=20)),
                ('produto_id', models.CharField(max_length=20)),
                ('produto_nome', models.CharField(max_length=200)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_vendida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_promocional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto_preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabricante', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'produtos_vendidos',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('venda_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cliente_id', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('vendedor', models.CharField(max_length=20)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vendas',
            },
        ),
    ]
